# Beee build helper.
# On first run (no beee_config.json) it asks for the COM port, language and WiFi
# credentials, saves them to beee_config.json (git-ignored), generates secrets.h,
# then compiles and uploads the firmware.

$ErrorActionPreference = "Stop"
$root      = Split-Path -Parent $MyInvocation.MyCommand.Path
$cfgPath   = Join-Path $root "beee_config.json"
$fwDir     = Join-Path $root "esp32_firmware"
$secretsPath = Join-Path $fwDir "src\secrets.h"

Write-Host "=========================================="
Write-Host "   Beee - build and flash"
Write-Host "=========================================="

if (-not (Test-Path $cfgPath)) {
    Write-Host ""
    Write-Host "First run: let's configure Beee."
    Write-Host ""
    $com = Read-Host "COM port (e.g. COM3)"
    $lang = Read-Host "Language [fr/en] (default: fr)"
    if ([string]::IsNullOrWhiteSpace($lang)) { $lang = "fr" }
    $ssid = Read-Host "WiFi network name (SSID)"
    $pass = Read-Host "WiFi password"

    $obj = [ordered]@{
        com_port      = $com
        language      = $lang.ToLower()
        wifi_ssid     = $ssid
        wifi_password = $pass
    }
    $obj | ConvertTo-Json | Set-Content -Path $cfgPath -Encoding UTF8
    Write-Host "Saved configuration to beee_config.json"
}

# Load config
$cfg = Get-Content -Raw $cfgPath | ConvertFrom-Json
$com = $cfg.com_port
$langMacro = if ($cfg.language -eq "en") { "BEEE_LANG_EN" } else { "BEEE_LANG_FR" }

# Generate secrets.h
$secrets = @"
#ifndef SECRETS_H
#define SECRETS_H
// Auto-generated by build.ps1 from beee_config.json. Do NOT commit.
#define WIFI_SSID     "$($cfg.wifi_ssid)"
#define WIFI_PASSWORD "$($cfg.wifi_password)"
#define $langMacro
#endif // SECRETS_H
"@
Set-Content -Path $secretsPath -Value $secrets -Encoding ASCII
Write-Host "Generated secrets.h (language: $langMacro, port: $com)"
Write-Host ""

# Locate PlatformIO: PATH first, then the standard install location, then python module.
$pioExe = $null
if (Get-Command pio -ErrorAction SilentlyContinue) {
    $pioExe = "pio"
} elseif (Test-Path "$env:USERPROFILE\.platformio\penv\Scripts\pio.exe") {
    $pioExe = "$env:USERPROFILE\.platformio\penv\Scripts\pio.exe"
}

# Build and upload
Push-Location $fwDir
try {
    if ($pioExe) {
        & $pioExe run --target upload --upload-port $com
    } elseif (Get-Command python -ErrorAction SilentlyContinue) {
        python -m platformio run --target upload --upload-port $com
    } else {
        Write-Host "PlatformIO not found. Install it with: pip install platformio"
        exit 1
    }
} finally {
    Pop-Location
}
