#ifndef CONFIG_H
#define CONFIG_H

// --- WiFi credentials & language ---
// These are NOT stored in git. They live in secrets.h, generated by build.bat
// (or build.ps1) from beee_config.json. See secrets.example.h for the format.
#if __has_include("secrets.h")
  #include "secrets.h"
#else
  #warning "secrets.h not found: run build.bat (or copy secrets.example.h to secrets.h). Using placeholder WiFi credentials."
  #define WIFI_SSID "CHANGE_ME"
  #define WIFI_PASSWORD "CHANGE_ME"
#endif

// Default UI language if secrets.h did not set one (BEEE_LANG_EN / BEEE_LANG_FR)
#if !defined(BEEE_LANG_EN) && !defined(BEEE_LANG_FR)
  #define BEEE_LANG_FR
#endif

// LCD Screen Pin Configurations (JD9853 Driver over SPI)
#define LCD_CS   21
#define LCD_SCK  38
#define LCD_MOSI 39
#define LCD_DC   45
#define LCD_RST  40
#define LCD_BL   46

// Touch Panel Pin Configurations (AXS5106L Driver over I2C)
#define TOUCH_SDA 42
#define TOUCH_SCL 41
#define TOUCH_RST 47
#define TOUCH_INT 48

// Screen Dimensions
#define SCREEN_WIDTH  172
#define SCREEN_HEIGHT 320
#define SCREEN_ROTATION 0 // 0 = portrait, 1 = landscape, 2 = inverted portrait, 3 = inverted landscape

#endif // CONFIG_H
