#ifndef SECRETS_H
#define SECRETS_H

// Template for secrets.h. The real secrets.h is generated by build.bat / build.ps1
// from beee_config.json and is excluded from git (see .gitignore).
// You can also copy this file to secrets.h and fill it in manually.

#define WIFI_SSID     "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

// UI language: define exactly one of these.
#define BEEE_LANG_FR
// #define BEEE_LANG_EN

#endif // SECRETS_H
